from typing import Optional, TYPE_CHECKING

from .constants import _XML_TAG_ATTRIBUTE, _XML_TAG_COLLECTION, _XML_TAG_REFERENCE
from .helpers import _get_extension_attr, _get_extensions_map, _set_slot_or_extension

if TYPE_CHECKING:
    from .class_ import Class


class Field:
    """
    A class representing columns on database tables
    ===============================================

    The base class for attributes, references and collections. All
    columns in DB tables are represented by fields

    SYNOPSIS
    --------

        >>> service = Service("https://www.flymine.org/query/service")
        >>> model = service.model
        >>> cd = model.get_class("Gene")
        >>> print("Gene has", len(cd.fields), "fields")
        >>> for field in gene_cd.fields:
        ...        print(" - ", field)
        Gene has 45 fields
            -  CDSs is a group of CDS objects, which link back to this as gene
            -  GLEANRsymbol is a String
            -  UTRs is a group of UTR objects, which link back to this as gene
            -  alleles is a group of Allele objects, which link back
               to this as gene
            -  chromosome is a Chromosome
            -  chromosomeLocation is a Location
            -  clones is a group of CDNAClone objects, which link
               back to this as gene
            -  crossReferences is a group of CrossReference objects,
                which link back to this as subject
            -  cytoLocation is a String
            -  dataSets is a group of DataSet objects,
                which link back to this as bioEntities
            -  downstreamIntergenicRegion is a IntergenicRegion
            -  exons is a group of Exon objects,
                which link back to this as gene
            -  flankingRegions is a group of GeneFlankingRegion objects,
                which link back to this as gene
            -  goAnnotation is a group of GOAnnotation objects
            -  homologues is a group of Homologue objects,
                which link back to this as gene
            -  id is a Integer
            -  interactions is a group of Interaction objects,
                which link back to this as gene
            -  length is a Integer
            ...

    @see: L{Attribute}
    @see: L{Reference}
    @see: L{Collection}
    """

    __slots__ = ("name", "type_name", "type_class", "declared_in", "_extensions")

    def __init__(self, name: str, type_name: str, class_origin: "Class") -> None:
        """
        Constructor - DO NOT USE
        ========================

        THIS CLASS IS NOT MEANT TO BE INSTANTIATED DIRECTLY

        you are unlikely to need to do
        so anyway: it is recommended you access fields
        through the classes generated by the model

        @param name: The name of the reference
        @param type_name: The name of the model.Class this refers to
        @param class_origin: The model.Class this was declared in

        """
        self.name: str = name
        self.type_name: str = type_name
        self.type_class: Optional["Class"] = None
        self.declared_in: "Class" = class_origin
        self._extensions = None

    def __repr__(self) -> str:
        return self.name + " is a " + self.type_name

    def __str__(self) -> str:
        return self.name

    @property
    def fieldtype(self) -> str:
        raise Exception("Fields should never be directly instantiated")

    @property
    def extensions(self):
        return _get_extensions_map(self)

    def __setattr__(self, name, value):
        _set_slot_or_extension(self, name, value)

    def __getattr__(self, name):
        return _get_extension_attr(self, name)


class Attribute(Field):
    """
    Attributes represent columns that contain actual data
    =====================================================

    The Attribute class inherits all the behaviour of L{intermine314.model.Field}
    """

    __slots__ = ()

    @property
    def fieldtype(self) -> str:
        return _XML_TAG_ATTRIBUTE


class Reference(Field):
    """
    References represent columns that refer to records in other tables
    ==================================================================

    In addition the the behaviour and properties of Field, references
    may also have a reverse reference, if the other record points
    back to this one as well. And all references will have their
    type upgraded to a type_class during parsing
    """

    __slots__ = ("reverse_reference_name", "reverse_reference")

    def __init__(
        self,
        name: str,
        type_name: str,
        class_origin: "Class",
        reverse_ref: Optional[str] = None,
    ) -> None:
        """
        Constructor
        ===========

        In addition to the a parameters of Field, Reference also
        takes an optional reverse reference name (str)

        @param name: The name of the reference
        @param type_name: The name of the model.Class this refers to
        @param class_origin: The model.Class this was declared in
        @param reverse_ref: The name of the reverse reference (default: None)

        """
        self.reverse_reference_name: Optional[str] = reverse_ref
        super(Reference, self).__init__(name, type_name, class_origin)
        self.reverse_reference: Optional["Reference"] = None

    def __repr__(self) -> str:
        """
        Return a string representation
        ==============================

        @rtype: str
        """
        s = super(Reference, self).__repr__()
        if self.reverse_reference is None:
            return s
        else:
            return s + ", which links back to this as " + self.reverse_reference.name

    @property
    def fieldtype(self) -> str:
        return _XML_TAG_REFERENCE


class Collection(Reference):
    """
    Collections are references which refer to groups of objects
    ===========================================================

    Collections have all the same behaviour and properties as References
    """

    __slots__ = ()

    def __repr__(self) -> str:
        """Return a string representation"""
        ret = super(Collection, self).__repr__().replace(" is a ", " is a group of ")
        if self.reverse_reference is None:
            return ret + " objects"
        else:
            return ret.replace(", which links", " objects, which link")

    @property
    def fieldtype(self) -> str:
        return _XML_TAG_COLLECTION
