"""Shared constants for intermine314 runtime defaults."""

DEFAULT_PARALLEL_WORKERS = 16
DEFAULT_PARALLEL_PAGE_SIZE = 1000
DEFAULT_KEYSET_BATCH_SIZE = 2000
DEFAULT_KEYSET_AUTO_MIN_SIZE = 50_000

DEFAULT_QUERY_THREAD_NAME_PREFIX = "intermine314-query"
DEFAULT_EXPORT_BATCH_SIZE = 10_000

DEFAULT_LIST_CHUNK_SIZE = 10_000
DEFAULT_TARGETED_EXPORT_PAGE_SIZE = 5_000
DEFAULT_TARGETED_LIST_NAME_PREFIX = "intermine314_targeted_chunk"
DEFAULT_TARGETED_LIST_DESCRIPTION = "Temporary chunk list for targeted benchmark export"
DEFAULT_TARGETED_LIST_TAGS = ("intermine314", "benchmark", "targeted")
