[profiles.default]
ordered = "ordered"
large_query_mode = false

[profiles.large_query]
ordered = "window"
large_query_mode = true

[profiles.unordered]
ordered = "unordered"
large_query_mode = false

[profiles.mostly_ordered]
ordered = "window"
large_query_mode = false
