[benchmark_profiles.server_restricted]
include_legacy_baseline = true
workers = [3, 6, 9]

[benchmark_profiles.non_restricted]
include_legacy_baseline = true
workers = [4, 8, 12, 16]

[defaults.mine]
benchmark_profile = "non_restricted"

[mines.legumemine]
benchmark_profile = "server_restricted"

[mines.maizemine]
benchmark_profile = "server_restricted"

[mines.thalemine]
benchmark_profile = "non_restricted"

[mines.oakmine]
benchmark_profile = "non_restricted"

[mines.wheatmine]
benchmark_profile = "non_restricted"
