[profiles.default]
ordered = "unordered"
large_query_mode = false

[profiles.large_query]
ordered = "unordered"
large_query_mode = true

[profiles.unordered]
ordered = "unordered"
large_query_mode = false
